import type {Metadata} from "next";
import {Public_Sans} from "next/font/google";
import "./globals.css";
import Layouts from "@/layouts/layouts";

const publicSans = Public_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${publicSans.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Layouts>{children}</Layouts>
      </body>
    </html>
  );
}
